# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9f8441bbb80ae15fd91648b3e5ab73bb421bd4852e913bbf56276f89dab70c406e919ee2fef44ad50d35bcf83c68f1608d8fdebbda333906dba7fdbece6cc04
  aws_access_key_id: <%= ['AWS_ACCESS_KEY_ID']%>
  aws_secret_access_key: <%= ['AWS_SECRET_ACCESS_KEY'] %>

test:
  secret_key_base: 36f6c89caecf389c014aa519850b839819efaac4ee0096e92fb5665577df9443008a146f3cf9ef7467da17e232ccd1dae6f84b71ab7cce74fdc6f686e344377d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
